# service/nodejs/docker/Dockerfile.serverTest
FROM node:latest

USER node

WORKDIR /app/server

# 依存パッケージインストール用に package.json (および yarn.lock があれば) をコピー
COPY ../server/package.json ./
# COPY ../server/yarn.lock ./  ← yarn.lock を管理している場合は有効にしてください
RUN yarn install

WORKDIR /app/serverTest

# 依存パッケージインストール用に package.json (および yarn.lock があれば) をコピー
COPY ../serverTest/package.json ./
# COPY ../server/yarn.lock ./  ← yarn.lock を管理している場合は有効にしてください
RUN yarn install

USER root
ARG UID
ARG GID

RUN groupmod -g ${GID} node && \
    usermod -u ${UID} -g ${GID} node && \
    chown -R node:node /app

USER node

CMD ["yarn", "test"]

