services:
  nodejs:
    container_name: ${PROJECT_NAME}-server-test-nodejs
    build:
      context: ../service/nodejs
      dockerfile: setting/docker/Dockerfile.serverTest
      args:
        UID: ${UID}
        GID: ${GID}
    working_dir: /app/serverTest
    command: yarn test
    volumes:
      - ../service/nodejs/core/server:/app/server:delegated
      - ../service/nodejs/core/client:/app/server/client:delegated
      - ../service/nodejs/test/serverTest:/app/serverTest:delegated
      - nodemodules-server:/app/server/node_modules
      - nodemodules-serverTest:/app/serverTest/node_modules
    ports:
      - "4000:3000"
    environment:
      - NODE_ENV=test
    user: "${UID}:${GID}"

volumes:
  nodemodules-server:
    name: ${PROJECT_NAME}-server-test-nodejs-nodemodules-server
  nodemodules-serverTest:
    name: ${PROJECT_NAME}-server-test-nodejs-nodemodules-serverTest

